---
# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: nvim
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# Preference for editor-based interactive prompting. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prefer_editor_prompt: disabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    me: api user --jq ".login"
    as: auth status
    sa: auth switch
    prs: pr list
    open: repo view --web
    bugs: issue list --label="bugs"
    myissues: issue list --author "@me" --state open
    repo-path: repo view --json nameWithOwner -q .nameWithOwner
    # co: pr checkout
    co: '!$HOME/.marslo/bin/gh-ops --checkout'
    cl: '!$HOME/.marslo/bin/gh-ops --close'
    squash-clean: '!sh -c "$HOME/.marslo/bin/gh-ops --squash -- --delete-branch \"\$@\"" --'
    rebase-clean: '!sh -c "$HOME/.marslo/bin/gh-ops --rebase -- --delete-branch \"\$@\"" --'
    # propen: pr view --web
    pr-new: '!$HOME/.marslo/bin/gh-new --open'
    pro: '!$HOME/.marslo/bin/gh-new --open --auto'
    pr-open: '!$HOME/.marslo/bin/gh-ops --open'
    pr-close: '!$HOME/.marslo/bin/gh-ops --close'
    pr-label: '!$HOME/.marslo/bin/gh-ops --label'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
# Whether to display labels using their RGB hex color codes in terminals that support truecolor. Supported values: enabled, disabled
color_labels: enabled
# Whether customizable, 4-bit accessible colors should be used. Supported values: enabled, disabled
accessible_colors: enabled
# Whether an accessible prompter should be used. Supported values: enabled, disabled
accessible_prompter: enabled
# Whether to use a animated spinner as a progress indicator. If disabled, a textual progress indicator is used instead. Supported values: enabled, disabled
spinner: enabled
